# Basic
title:  LW
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/louiswi/louiswi.github.io" target="_blank">Louiswi's blog</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://louiswi.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/louiswi/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: lwgithubpage
    # duoshuo: 
    
# Social
social:
    weibo: louiswi
    github: louiswi
    twitter: louiswi
    gplus: louiswi
    mail: llouiswi@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
